### ISSUE TITLE
Assist.dll detected as a Trojan

### ISSUE THREAD

**Issue by obstrasium** [HeyM1ke/Assist#198]
Microsoft Defender detected and quarantined the Assist.exe file within the portable package as a Trojan:Win32/Wacatac.A!ml. Scanning it with VirusTotal gives 31/73 vendors detecting it as some form of trojan. Even by false positive standards, this is a bit too suspicious.

<img width="1120" alt="msedge_UCQeAkQHQ6" src="https://github.com/HeyM1ke/Assist/assets/90981666/c0978f5c-5344-497b-9094-fdab3dd05b3e">

**Comment by HeyM1ke** [comment]
Honestly this is pretty annoying. At this point, I'm not exactly sure on what to do. Just extremely annoying I guess.

**Comment by HeyM1ke** [comment]
Just ran a scan myself with the latest version, and it only showed 2. I would redownload (here)[Https://assistval.com/] just in case, but otherwise I am unsure.

https://www.virustotal.com/gui/file/cdb3c8d5bb9aa19f4517be827d456730beaa10022adb437ddce0b186d6e3c7f9
![image](https://github.com/HeyM1ke/Assist/assets/49486947/d8dcc94f-2b1c-4982-9261-d1bc90b574b1)
