### ISSUE TITLE
Assist Starting Delay

### ISSUE THREAD

**Issue by ClawLuca** [HeyM1ke/Assist#92]
![image](https://user-images.githubusercontent.com/71341749/171417486-b0433ae0-f020-4be2-a045-650f200fb5eb.png)

I have a problem where my assist takes 10 minutes to fully load. Starting the game also takes about 5 minutes. Am I missing just one simple thing? Procedure: Assist starts and the skins in the store load in one by one. When I go to my ingame Shop in the navigation panel, everything reloads even if I switch back to the main page which was already completely loaded before.

![image](https://user-images.githubusercontent.com/71341749/171417687-dbfbb0e3-072d-4628-a31d-3c1e7c524bfb.png)
 The second picture shows a screenshot of me starting the game. It takes like 3 minutes until my game starts and the screen disappears.

**Comment by mustachebutter** [comment]
Apps taking a long time to load might be because whichever drive you installed them on is almost full and it takes them a while trying to grab the files they need. This is strictly hypothetical as I don't really have proof backing this up aside my own experience. I have a decent PC and my drive Z:, where I installed all the games take a bit of time to load up as well.

However, I have rarely came across this problem for Assist even my drive is almost full. Might want to check your Internet speed too? I can't replicate this on my machine.

**Comment by ClawLuca** [comment]
I probably just have to live with it. My drive contains 1TB/2TB and its the fastest m.2 ssd on the market. My Internet speed is very decent and i have no problem ingame with my internet.

**Comment by mustachebutter** [comment]
That's really odd indeed. That is overkill for a small app like this. I have no problem / no significant delay launching Assist. Try re-installing the app? I don't know if it would help (high chance that it wouldn't), but it's worth a try.
